# Generated by Django 5.2.7 on 2025-10-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbJourney', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='title',
            new_name='name',
        ),
    ]
